# -*- coding: utf-8 -*-
"""
api.py

FastAPI wrapper around rag_chain.RecommendationEngine.
Bilingual (French / English).

Endpoints:
    GET  /health              -- liveness check
    POST /recommend           -- structured input (crop+disease+language),
                                  ZERO live LLM calls -- pure lookup.
    POST /chat                -- free-text question, auto-detected
                                  language, LLM used for extraction +
                                  conversational reformulation only.

Both endpoints can return match_type="ambiguous": this happens when the
requested disease is a generic umbrella term (e.g. "rust" / "rouille")
that corresponds to SEVERAL distinct diseases for the given crop (e.g.
wheat leaf rust vs stem rust vs stripe rust -- different treatments).
Rather than guessing and silently blending unrelated products together,
the API asks for clarification and lists the specific options.

Usage:
    uvicorn api:app --reload --port 8000

Example request:
    POST /recommend
    {"crop": "tomato", "disease": "Late Blight", "language": "fr"}

    POST /chat
    {"question": "comment traiter le mildiou sur mes tomates ?"}
"""

import json
import logging
from contextlib import asynccontextmanager

from fastapi import FastAPI, HTTPException
from fastapi.responses import RedirectResponse
from pydantic import BaseModel, Field
from langdetect import detect, LangDetectException

from rag_chain import RecommendationEngine, normalize_language


logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("api")


# ============================================================
# NOTE ON RESPONSE STRUCTURE
# ============================================================
#
# "traitement_recommande" is NOT generated by the LLM -- it's built
# directly from structured pesticide data in chunks.jsonl metadata
# (RecommendationEngine.retrieve()'s `products` field). This is both
# more reliable (no risk of the LLM skipping/garbling entries on long
# lists, and zero risk of mistranslating a regulated substance name or
# dosage) and produces a proper JSON array instead of a text blob.
#
# "gestion_maladie" and "conseils_preventifs" are ALSO not generated
# live -- they were precomputed ONCE (offline, via
# precompute_translations.py) from the raw list items in each chunk,
# with automatic validation + manual review. /recommend therefore makes
# ZERO calls to the LLM in the normal case: it is a deterministic,
# auditable lookup.
#
# /chat is different on purpose: each question is unique free text, so
# there's no fixed corpus to pre-validate. The LLM there (a) extracts
# crop/disease from the question, then (b) reformulates the same
# precomputed, verified information into natural conversational prose.
# The LLM is never asked to invent facts in either endpoint.


# ============================================================
# LANGUAGE DETECTION (pour /chat)
# ============================================================

def detect_language(text: str) -> str:
    """
    Returns 'fr' or 'en'. Defaults to 'fr' when detection fails (very
    short text, ambiguous, etc.).
    """
    try:
        lang = detect(text)
        return "en" if lang == "en" else "fr"
    except LangDetectException:
        return "fr"


# ============================================================
# EXTRACTION CROP/DISEASE DEPUIS UNE QUESTION LIBRE (pour /chat)
# ============================================================

EXTRACTION_PROMPT = {
    "fr": """Tu extrais crop et disease d'une question agricole.

Reponds UNIQUEMENT en JSON, rien d'autre, sans markdown, sans backticks:
{{"crop": "nom de la culture en anglais (ex: tomato, grapevine, olive, citrus, wheat, pepper, fig, potato) ou null si absent", "disease": "nom de la maladie en anglais ou null si absente"}}

Question: "{question}"

JSON:""",
    "en": """Extract crop and disease from an agricultural question.

Reply ONLY with JSON, nothing else, no markdown, no backticks:
{{"crop": "crop name in English (e.g. tomato, grapevine, olive, citrus, wheat, pepper, fig, potato) or null if absent", "disease": "disease name in English or null if absent"}}

Question: "{question}"

JSON:""",
}


def extract_crop_disease(question: str, language: str):
    raw = engine.llm.invoke(
        EXTRACTION_PROMPT[language].format(question=question)
    ).content
    raw = raw.replace("```json", "").replace("```", "").strip()
    try:
        data = json.loads(raw)
        return data.get("crop"), data.get("disease")
    except json.JSONDecodeError:
        logger.warning(f"Extraction JSON invalide ({language}): {raw!r}")
        return None, None


# ============================================================
# REFORMULATION EN PROSE (pour /chat)
# ============================================================

REFORMULATION_PROMPT = {
    "fr": """Tu es un assistant agricole qui parle a des agriculteurs tunisiens.

Voici des informations techniques, deja verifiees et exactes :

Produits homologues et dosages :
{products_text}

Gestion de la maladie (une fois presente) :
{gestion_maladie}

Conseils preventifs (pour eviter son apparition) :
{conseils_preventifs}

Question originale de l'utilisateur : {question}

Reformule ces informations en un texte naturel et fluide, comme si tu parlais directement a l'agriculteur, en repondant a sa question precise.
REGLES IMPORTANTES :
- Reponds ENTIEREMENT en francais, aucun mot anglais.
- N'invente RIEN, n'ajoute AUCUNE information qui n'est pas deja ci-dessus.
- Garde TOUTES les valeurs exactes (noms de produits, dosages, unites) -- ne les arrondis pas, ne les resume pas.
- Tu peux garder des retours a la ligne ou des tirets pour les listes, mais evite le ton "formulaire administratif".
- Si une information n'est pas specifiee, integre ca naturellement plutot que de recopier la phrase telle quelle.
- Ne reponds qu'aux aspects que l'utilisateur a demandes si sa question est specifique (ex: si il demande juste le dosage, concentre-toi la-dessus), sinon donne une vue d'ensemble.

Reponse reformulee :""",
    "en": """You are an agricultural assistant speaking to Tunisian farmers.

Here is technical information, already verified and accurate:

Registered products and dosages:
{products_text}

Disease management (once present):
{gestion_maladie}

Preventive advice (to avoid it appearing):
{conseils_preventifs}

Original user question: {question}

Rephrase this information into natural, fluent text, as if speaking directly to the farmer, answering their specific question.
IMPORTANT RULES:
- Answer ENTIRELY in English, no French words.
- Do NOT invent anything, do NOT add any information not already above.
- Keep ALL exact values (product names, dosages, units) -- do not round or summarize them.
- You can keep line breaks or dashes for lists, but avoid a "form-filling" tone.
- If information is not specified, phrase that naturally instead of copying the sentence verbatim.
- Only answer the aspects the user actually asked about if their question is specific (e.g. if they only ask about dosage, focus on that), otherwise give an overview.

Rephrased answer:""",
}


def format_products_for_prompt(products: list, language: str) -> str:
    if not products:
        return (
            "Aucun produit homologué trouvé dans le catalogue."
            if language == "fr"
            else "No registered product found in the catalog."
        )
    lines = []
    for p in products:
        lines.append(
            f"- {p.get('produit', '')} ({p.get('substance_active', '')}) : "
            f"dosage {p.get('dosage', '')}, homologation {p.get('homologation', '')}"
        )
    return "\n".join(lines)


def reformulate_answer(products_text: str, gestion_maladie: str,
                        conseils_preventifs: str, question: str, language: str) -> str:
    raw = engine.llm.invoke(
        REFORMULATION_PROMPT[language].format(
            products_text=products_text,
            gestion_maladie=gestion_maladie,
            conseils_preventifs=conseils_preventifs,
            question=question,
        )
    ).content
    return raw.strip()


# ============================================================
# REQUEST / RESPONSE MODELS
# ============================================================

class RecommendRequest(BaseModel):
    crop: str = Field(..., description="Crop name, e.g. 'tomato', 'tomate'.", min_length=1)
    disease: str = Field(..., description="Disease name, e.g. 'Late Blight'.", min_length=1)
    language: str = Field(default="fr", description="'fr' or 'en'.")


class ProductTreatment(BaseModel):
    produit: str | None = None
    substance_active: str | None = None
    dosage: str | None = None
    homologation: str | None = None
    utilisation: str | None = None
    confiance: str = "haute"   # "haute" | "medium" (mirrors FOUND vs FOUND_LOW_CONFIDENCE)

    # Only set when match_type is "semantic": tags which crop/disease this
    # specific product was actually registered for, since a
    # semantic-fallback answer can blend chunks from DIFFERENT
    # crops/diseases. Null for exact/fuzzy matches, where every product
    # is necessarily from the correct crop+disease already.
    source_crop: str | None = None
    source_disease: str | None = None


class RecommendationResponse(BaseModel):
    crop: str
    disease: str
    language: str

    traitement_recommande: list[ProductTreatment]
    gestion_maladie: str        # actions once the disease is present
    conseils_preventifs: str    # actions to prevent it before it appears

    match_type: str          # "exact" | "fuzzy" | "semantic" | "ambiguous" | "none"
    confidence: str          # "high" | "medium" | "low"
    is_approximate_match: bool
    avertissement: str | None   # human-readable warning when is_approximate_match

    # Populated only when match_type == "ambiguous": the specific
    # diseases the caller should choose between (e.g. leaf/stem/stripe
    # rust). Empty otherwise.
    clarification_needed: bool
    disease_options: list[str]

    pesticide_status: str | None
    matched_crop: str | None
    matched_disease: str | None
    source_chunk_ids: list[str]


class ChatRequest(BaseModel):
    question: str = Field(..., min_length=1)


class ChatResponse(BaseModel):
    response: str
    language: str
    matched_crop: str | None
    matched_disease: str | None
    match_type: str
    confidence: str
    avertissement: str | None
    clarification_needed: bool
    disease_options: list[str]


class HealthResponse(BaseModel):
    status: str
    corpus_size: int


# ============================================================
# APP + ENGINE LIFECYCLE
# ============================================================
#
# The engine (chunks + FAISS + Ollama connection) is loaded ONCE at
# startup, not per-request -- re-loading the embedding model or
# re-reading chunks.jsonl on every call would be needlessly slow.

engine: RecommendationEngine | None = None


@asynccontextmanager
async def lifespan(app: FastAPI):
    global engine
    logger.info("Loading RecommendationEngine...")
    engine = RecommendationEngine(lazy_faiss=True)
    logger.info(f"Engine ready. {len(engine.all_chunks)} chunk(s) loaded.")
    yield
    logger.info("Shutting down.")


app = FastAPI(
    title="Plant Disease Treatment Recommender",
    description=(
        "Recommends registered pesticide treatments for a given crop + "
        "disease, based on the official Tunisian pesticide catalog and "
        "agronomic fact sheets. Bilingual: French and English. "
        "/recommend is a fully deterministic lookup (no live LLM calls); "
        "/chat adds free-text understanding and conversational "
        "reformulation on top of the same verified data. Both endpoints "
        "ask for clarification instead of guessing when a disease name "
        "is ambiguous (e.g. generic 'rust'/'rouille')."
    ),
    version="2.1.0",
    lifespan=lifespan,
)


# ============================================================
# ENDPOINTS
# ============================================================

@app.get("/", include_in_schema=False)
def root():
    return RedirectResponse(url="/docs")


@app.get("/health", response_model=HealthResponse)
def health():
    if engine is None:
        raise HTTPException(status_code=503, detail="Engine not ready.")
    return HealthResponse(status="ok", corpus_size=len(engine.all_chunks))


@app.post("/recommend", response_model=RecommendationResponse)
def recommend(request: RecommendRequest):
    if engine is None:
        raise HTTPException(status_code=503, detail="Engine not ready.")

    crop = request.crop.strip()
    disease = request.disease.strip()
    language = normalize_language(request.language)

    if not crop or not disease:
        raise HTTPException(status_code=422, detail="crop and disease must be non-empty.")

    try:
        result = engine.recommend(crop, disease, language=language)
    except Exception as e:
        logger.exception("Error while generating recommendation")
        raise HTTPException(status_code=500, detail=f"Recommendation failed: {e}")

    if result["match_type"] == "none":
        raise HTTPException(
            status_code=404,
            detail=(
                f"No information found for crop='{crop}', disease='{disease}' "
                f"in the current knowledge base."
            ),
        )

    return RecommendationResponse(
        crop=crop,
        disease=disease,
        language=result["language"],
        traitement_recommande=[ProductTreatment(**p) for p in result["products"]],
        gestion_maladie=result["gestion_maladie"],
        conseils_preventifs=result["conseils_preventifs"],
        match_type=result["match_type"],
        confidence=result["confidence"],
        is_approximate_match=(result["match_type"] == "semantic"),
        avertissement=result.get("warning"),
        clarification_needed=(result["match_type"] == "ambiguous"),
        disease_options=result.get("ambiguous_options", []),
        pesticide_status=result.get("pesticide_status"),
        matched_crop=result.get("matched_crop"),
        matched_disease=result.get("matched_disease"),
        source_chunk_ids=result["chunk_ids"],
    )


@app.post("/chat", response_model=ChatResponse)
def chat(request: ChatRequest):
    if engine is None:
        raise HTTPException(status_code=503, detail="Engine not ready.")

    question = request.question.strip()
    if not question:
        raise HTTPException(status_code=422, detail="question must be non-empty.")

    language = detect_language(question)
    crop, disease = extract_crop_disease(question, language)

    if not crop or not disease:
        no_match_text = {
            "fr": (
                "Je n'ai pas identifié clairement la culture et/ou la maladie "
                "dans votre question. Pouvez-vous préciser, par exemple : "
                "\"comment traiter le mildiou sur mes tomates ?\""
            ),
            "en": (
                "I couldn't clearly identify the crop and/or disease in your "
                "question. Could you be more specific, for example: "
                "\"how do I treat late blight on my tomatoes?\""
            ),
        }[language]
        return ChatResponse(
            response=no_match_text,
            language=language,
            matched_crop=crop,
            matched_disease=disease,
            match_type="none",
            confidence="low",
            avertissement=None,
            clarification_needed=False,
            disease_options=[],
        )

    try:
        result = engine.recommend(crop, disease, language=language)
    except Exception as e:
        logger.exception("Error while generating chat response")
        raise HTTPException(status_code=500, detail=f"Chat failed: {e}")

    if result["match_type"] == "none":
        not_found_text = {
            "fr": f"Je n'ai pas trouvé d'information pour '{disease}' sur '{crop}' dans la base actuelle.",
            "en": f"I couldn't find information for '{disease}' on '{crop}' in the current knowledge base.",
        }[language]
        return ChatResponse(
            response=not_found_text,
            language=language,
            matched_crop=None,
            matched_disease=None,
            match_type="none",
            confidence="low",
            avertissement=None,
            clarification_needed=False,
            disease_options=[],
        )

    if result["match_type"] == "ambiguous":
        # Ask directly -- no reformulation LLM call needed here, the
        # clarification message is already precise and short.
        return ChatResponse(
            response=result["gestion_maladie"],  # holds the clarification message
            language=language,
            matched_crop=result.get("matched_crop"),
            matched_disease=None,
            match_type="ambiguous",
            confidence="low",
            avertissement=None,
            clarification_needed=True,
            disease_options=result.get("ambiguous_options", []),
        )

    products_text = format_products_for_prompt(result["products"], language)

    reformulated = reformulate_answer(
        products_text,
        result["gestion_maladie"],
        result["conseils_preventifs"],
        question,
        language,
    )

    return ChatResponse(
        response=reformulated,
        language=result["language"],
        matched_crop=result.get("matched_crop"),
        matched_disease=result.get("matched_disease"),
        match_type=result["match_type"],
        confidence=result["confidence"],
        avertissement=result.get("warning"),
        clarification_needed=False,
        disease_options=[],
    )


if __name__ == "__main__":
    # Allows `python api.py` as a convenience alternative to
    # `uvicorn api:app --reload`. The --reload flag (auto-restart on code
    # changes) only works with the CLI form, so prefer that during active
    # development; this is just here so the file doesn't silently do
    # nothing when run directly.
    import uvicorn
    uvicorn.run(app, host="127.0.0.1", port=8000)
